[[extensions]]
name = "app-triggers"
type = "flow_trigger"
handle = "app-triggers"
description = "Your description"

[settings]

  [[settings.fields]]
  type = "customer_reference"

  [[settings.fields]]
  type = "single_line_text_field"
  key = "Your field key"